var board = [
  {
    "position": "Board Chairman",
    "fullName": "J.L. Martinez",
    "credentials": "President, 27 Consulting",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Ben Amaba, PhD",
    "credentials": "Worldwide Executive, PE, CPIM®, LEED® AP",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Tommy Boroughs",
    "credentials": "Partner, Holland & Knight, LLP",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Timothy L. Bryant",
    "credentials": "PE, Senior Manager External Affairs, NextEra Energy, Inc.",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Gustavo R. Cepero",
    "credentials": "Vice President, Florida Crystals Corporation",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Christopher Fountas",
    "credentials": "Partner, Arsenal Venture Partners",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Nick Gladding",
    "credentials": "Attorney at Law, PA",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Jennifer Grove",
    "credentials": "Community Development Manager, Gulf Power Company",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Dan Holladay",
    "credentials": "Executive Director, BRIDG, University of Central Florida ORC",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Byron A. Knibbs",
    "credentials": "Vice President, Sustainable Services Dept, Orlando Utilities Commission",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Tom Lawery",
    "credentials": "Wholesale Renewables Manager, Distributed Energy Resources, Duke Energy",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Richard Paul-Hus",
    "credentials": "President - INcomm, Owner - Hypower",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Roy Periana",
    "credentials": "Director, Scripps Energy Laboratories",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Thomas L. Hernandez",
    "credentials": "Senior Vice President, Business Strategy and Renewables, Tampa Electric Company",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Jeremy L. Susac",
    "credentials": "Vice President, Government Affairs, Lennar Ventures",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Brian Yablonski",
    "credentials": "External Affairs Director, Gulf Power Company",
    "website": "",
    "headshot": "",
  },
  {
    "position": "Board member",
    "fullName": "Paul Zombo P.E.",
    "credentials": "Manager, Gas Turbine Engineering",
    "website": "",
    "headshot": "",
  },
]
 
