var content = [
  {
    "type": "research",
    "project": "Solar Systems Testing Facility",
    "authors": "James Roland, David Block",
    "description": "Over the past five years, the Florida Solar Energy Center (FSEC) has received a significant increase in demand for solar thermal and PV testing and certification. This occurrence has resulted in requiring the Center to correspondingly amplify its capabilities to respond to the increased demand. Thus, the objective of this task was to construct a solar thermal and PV systems testing facility. This facility was built by adding walls, windows, doors and air conditioning to an existing roof only facility at the FSEC site. This new facility provides laboratory space for testing of solar water heating components and systems and PV modules and inverters. At this time, the facility is completed and this is the final report for the project.",
    "budget": "600,609",
    "status": "completed",
    "university": "Florida Solar Energy Center, Unversity of Central Florida (UCF)",
    "website": "",
  },
  {
    "type": "research",
    "project": "Development of Novel Water Splitting Catalysts for the Production of Renewable Hydrogen",
    "authors": "Helena Hagelin-Weaver",
    "description": "This project focuses on the development of iron-based catalysts for the thermochemical splitting of water into hydrogen and oxygen. The thermochemical process of splitting water is particularly well-suited for the utilization of solar energy to provide the heat for the reaction and is a way to produce a renewable hydrogen fuel. As hydrogen is difficult to transport and store, producing hydrogen on site for power plants using proton exchange membrane (PEM) fuel cells or internal combustion engines to generate electricity or for the production of chemicals, such as liquid hydrocarbon fuels, is a very attractive approach. The project uses a two-step process in which water is passed over a reduced iron oxide to generate hydrogen while the oxygen is taken up by the oxygen-deficient iron oxide (Step 1: FeOx-1 + H2O -> FeOx + H2). In the second step the resulting iron oxide is heated to desorb oxygen and regenerate the oxygen-deficient iron oxide to close the catalytic cycle (Step 2: FeOx -> FeOx-1 + ½O2). The main objectives of the project are to develop mixed metal oxide catalysts that 1) will release oxygen at temperatures lower than 1500°C (Step 2), while still maintaining water-splitting activity (Step 1) and 2) are stable up to the temperature necessary for the oxygen desorption step.",
    "budget": "100,000",
    "status": "completed",
    "university": "University of Florida (UF)",
    "website": "",
  },
  {
    "type": "research",
    "project": "Solar Fuels for Thermochemical Cycles at Low Pressures",
    "authors": "David Hahn",
    "description": "The project focuses on the production of solar fuels from solar thermochemical cycles employing metal/metal oxide redox pairs. These thermochemical cycles consist of a high temperature endothermic solar driven reduction step and a low temperature, slightly exothermic water or CO2 splitting step. The high temperature step typically proceeds at temperatures above 2000 K. Hence, it poses a range of material and design challenges. According to Le Chatelier’s principle, the temperature for the solar dissociation reaction decreases as the pressure inside the reactor is reduced. The central hypothesis of the project is that operating the high temperature step of metal/metal oxide solar thermochemical cycles at reduced pressures will lead to significantly relaxed temperature requirements, while the work necessary to produce the pressure difference will not significantly reduce the overall efficiency of the process.The main goal of the project is to demonstrate the feasibility of carrying out high temperature thermal reduction of metal oxides in rarefied conditions using high intensity solar radiation from UF’s solar simulator.",
    "budget": "100,000",
    "status": "completed",
    "university": "University of Florida (UF)",
    "website": "",
  },
  {
    "type": "research",
    "project": "Concentrating Solar Power Program",
    "authors": "Charles Cromer",
    "description": "The objective of this effort is to produce a detailed map of Florida that shows the monthly solar direct beam and global resource available for the past eleven years. This solar resource map will give potential users or designers of solar systems, the solar input values for their location latitude and longitude and they will receive a table of solar energy monthly averages for that specific site as derived from the past eleven years of data. The concept employed to determine these solar values is to use NOAA satellite photos and utilize the brightness of the cloud cover as a clearness factor predictor of the solar resource that gets through to the ground below.",
    "budget": "50,000",
    "status": "completed",
    "university": "Florida Solar Energy Center, Unversity of Central Florida (UCF)",
    "website": "",
  },
  {
    "type": "research",
    "project": "Enhanced and Expanded Solar Thermal Test Capabilities",
    "authors": "J. Del Mar, R. Reedy",
    "description": "FSEC believes that independent, third-party testing and certification has extensive value in the marketplace, especially for products that are not widely “proven” with consumers such as solar water heating systems and solar electrical (photovoltaic) systems. In addition, due to the resurgence of the solar industry, FSEC has received a significant increase in demand for solar collector and solar system testing and certification. This occurrence has resulted in requiring the Center to correspondingly amplify its capabilities to respond to the increased demand This project has the objective of increasing FSEC’s solar thermal testing and certification activities by the following actions: test and analysis equipment and software upgrades and expansion, integration of the solar collector and system laboratories, enhancing documentation and reporting methods and streamlining and devising more comprehensive client test and certification application documents. Additional test facilities have come on-line internationally in the last two years and the increased testing capacity resulting from the additional tests labs has reduced the industry demand for FSEC’s thermal test services. FSEC however, remains the only test facility in the U.S. capable of testing certain types of solar thermal energy equipment and the current testing demand at FSEC still significantly exceeds the demand prior to 2008.",
    "budget": "809,295",
    "status": "completed",
    "university": "Florida Solar Energy Center, Unversity of Central Florida (UCF)",
    "website": "",
  },
  {
    "type": "research",
    "project": "Solar Thermal Power for Bulk Power and Distributed Generation",
    "authors": "David Hahn, James Klausner, Renwei Mei, Helena Weaver",
    "description": "While there are many different approaches to hydrogen generation, the most attractive means is to split water molecules using solar energy. The current approach is to develop highly reactive metal oxide materials to produce intermediary reactions that result in the splitting of water to produce hydrogen at moderate temperatures.",
    "budget": "446,000",
    "status": "completed",
    "university": "University of Florida",
    "website": "",
  },
  {
    "type": "research",
    "project": "Design, Construction and Operation of CSP Solar Thermal Power Plants in Florida",
    "authors": "Yogi Goswami, E. Stefanakos, M. Rahman, S. Aydin, R. Reddy",
    "description": "Florida utilities are mandated to achieve 20% renewable energy contribution to their generation mix by 2020. While technologically feasible with solar energy, the capital costs are high presently, capital costs range from $6,000-$7,000/kW for PV and $3,500-$4,000/kW for concentrating solar thermal power. This project targets the development of solar thermal power technology for bulk power and distributed generation, which will diversify energy resources in Florida and reduce greenhouse emissions by utilizing renewable sources. Also, there will be economic impacts with the establishment of new power industry in Florida, which will help the electrical utilities of the state to meet the renewable portfolio standards. The project has three main tasks; the first one is to develop design methodologies and standards for the proven solar thermal power technologies in combination with bio or fossil fuels based on Florida conditions and resources. Secondly, the project aims to set up demonstration and test facilities for these technologies for optimization for Florida conditions, and the final task is to develop and commercialize innovative technologies based on new thermodynamic cycles.",
    "budget": "882,000",
    "status": "completed",
    "university": "University of South Florida (USF), University of Florida (UF)",
    "website": "",
  },
  {
    "type": "article",
    "title": "Solar Photovoltaics at Home",
    "nameFull": "Hal S. Knowles, III",
    "date": "June 2015",
    "website": "http://www.myfloridahomeenergy.com/help/library/energy-services/home-solar-pv/",
    "photo": "",
  },
  {
    "type": "article",
    "title": "Passive Solar Orientation",
    "nameFull": "Kathleen C. Rupperta, Craig R. Millera, Christine Swansona, and Hyun-Jeong Leeb",
    "date": "May 2015",
    "website": "http://www.myfloridahomeenergy.com/help/library/choices/orientation/",
    "photo": "",
  },
  {
    "type": "article",
    "title": "The Story of a Collegiate Solar Champion",
    "nameFull": "Stuart Block",
    "date": "May 2015",
    "website": "http://www.myfloridahomeenergy.com/help/library/highlights/collegiate-solar-champion/",
    "photo": "",
  },
    {
    "type": "event",
    "title": "Florida Energy Summit",
    "location": "West Fort Lauderdale Beach Resort",
    "date": "Oct 18-20, 2017",
    "website": "http://www.floridaenergysummit.com/",
  },
  {
    "type": "education",
    "title": "Department of Mechanical and Aerospace Engineering Energy Certificate",
    "university": "University of Florida (UF)",
    "date": "",
    "website": "http://www.ufedge.ufl.edu/docs/brochures/brochure-energy_certificate.pdf",
    "photo": "",
  },
  {
    "type": "education",
    "title": "Alternative Energy Specialist Certificate",
    "university": "Eastern Florida State College (EFSC)",
    "date": "",
    "website": "http://madeinflorida.org/wp-content/uploads/2010/09/ESFC_BCC_0214.pdf",
    "photo": "",
  },
  {
    "type": "education",
    "title": "Photovoltaic Technology Certificate",
    "university": "Broward College",
    "date": "",
    "website": "http://www.broward.edu/academics/programs/Program%20Sheet%20Library/6307.pdf",
    "photo": "",
  },
  {
    "type": "education",
    "title": "Alternative Energy Certificate",
    "university": "Florida Keys Community College",
    "date": "",
    "website": "http://careertraining.ed2go.com/fkcc/sustainable-energy-green-programs",
    "photo": "",
  },
]
